### ISSUE TITLE
Calling jpy.get_type() too many times causes a memory access error

### ISSUE THREAD

**Issue by dpallison83** [bcdev/jpy#74] opened 2016-11-09 21:40 UTC
Running jpy 0.9, ran into this problem (running Windows):

    Process finished with exit code -1073741819 (0xC0000005)

briefly googling, appears this is a memory access error code, which is easily reproducible like so

    import jpy
    for i in range(200):
        jpy.get_type("java.lang.String")

The number of iterations it takes to bring up the error varies by class. I'd try to fix it myself, but I'm no expert with C.

**Comment by forman** [comment] 2016-11-11 09:08
Thanks for reporting this. Hope to fix it ASAP.

**Comment by voutilad** [comment] 2017-02-23 20:06
I can confirm it's an issue on macOS as well, so it's platform independent. Better error message, though:

```
Running /Users/dave/src/sisu-llc/jpy/src/test/python/jpy_gettype_test.py
....python(93039,0x7fffb94183c0) malloc: *** error for object 0x10f74a010: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
setting environment variable 'PYTHONPATH' to None
1 Python unit test(s) failed. Installation is likely broken.
```

**Comment by voutilad** [comment] 2017-02-23 22:35
See PR. Looks like a reference counting issue. The joys of embedded Python!

**Comment by bcdev** [comment] 2017-05-03 16:05
Seems to be fixed now. Carefully closing it.

**Closed** 2017-05-03 16:05 UTC
Labels: blocker, bug
